[package]
name = "craft-providers"
version.workspace = true
edition.workspace = true

[features]
bedrock = [
    "dep:aws-config",
    "dep:aws-sdk-bedrock",
    "dep:aws-sdk-bedrockruntime",
    "dep:aws-smithy-types",
    "dep:aws-smithy-runtime-api",
]

[dependencies]
aws-config = { workspace = true, optional = true }
aws-sdk-bedrock = { workspace = true, optional = true }
aws-sdk-bedrockruntime = { workspace = true, optional = true }
aws-smithy-types = { workspace = true, optional = true }
async-trait = { workspace = true }
aws-smithy-runtime-api = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
craft-storage = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
strum = { workspace = true }
flume = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }
base64 = { workspace = true }
sha2 = { workspace = true }
hmac = { workspace = true }
wait-timeout = { workspace = true }
fastrand = { workspace = true }
getrandom = { workspace = true }
open = { workspace = true }
craft-config = { workspace = true }
inventory = { workspace = true }
jiff = { workspace = true }

[dev-dependencies]
test-case = { workspace = true }
tempfile = { workspace = true }
