[package]
name = "craft-flow"
version.workspace = true
edition.workspace = true

[dependencies]
craft-agent = { workspace = true }
craft-config = { workspace = true }
craft-providers = { workspace = true }
craft-storage = { workspace = true }
craft-tool-macro = { workspace = true }
flume = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
test-case = { workspace = true }
tempfile = { workspace = true }
